module.exports = {
	A02650 : "Total income amount",
	A00100 : "Adjust gross income",
	A00101 : "Amount of AGI for itemized returns",
	A00200 : "Salaries and wages amount",
	A00300 : "Taxable interest amount",
	A00600 : "Ordinary dividends amount",
	A00650 : "Qualified dividends amount",
	A00700 : "State and local income tax refunds amount",
	A00900 : "Business or professional net income (less loss) amount",
	A01000 : "Net capital gain (less loss) amount",
	A01400 : "Taxable individual retirement arrangements distributions amount",
	A01700 : "Taxable pensions and annuities amount",
	A02300 : "Unemployment compensation amount",
	A02500 : "Taxable Social Security benefits amount",
	A02900 : "Total statutory adjustments amount",
	A03150 : "IRA payments amount",
	A03210 : "Number of returns with student loan interest deduction",
	A03220 : "Educator expenses amount",
	A03230 : "Tuition and fees deduction amount",
	A03240 : "Returns with domestic production activities deduction",
	A03270 : "Self-employment health insurance deduction amount",
	A03300 : "Self-employment retirement plans amount",
	A04470 : "Total itemized deductions amount",
	A04800 : "Taxable income amount",
	A05780 : "Excess advance premium tax credit repayment amount",
	A05800 : "Income tax before credits amount",
	A06500 : "Income tax amount",
	A07100 : "Total tax credits amount",
	A07180 : "Child and dependent care credit amount",
	A07220 : "Child tax credit amount",
	A07230 : "Nonrefundable education credit amount",
	A07240 : "Retirement savings contribution credit amount",
	A07260 : "Residential energy tax credit amount",
	A07300 : "Foreign tax credit amount",
	A09400 : "Self-employment tax amount",
	A09600 : "Alternative minimum tax amount",
	A09750 : "Health care individual responsibility payment amount",
	A10300 : "Total tax liability amount",
	A10600 : "Total tax payments amount",
	A10960 : "Refundable education credit amount",
	A11070 : "Additional child tax credit amount",
	A11560 : "Net premium tax credit amount",
	A11901 : "Tax due at time of filing amount",
	A11902 : "Overpayments refunded amount",
	A18300 : "Taxes paid amount",
	A18425 : "State and local income taxes amount",
	A18450 : "State and local general sales tax amount",
	A18500 : "Real estate taxes amount",
	A19300 : "Mortgage interest paid amount",
	A19700 : "Contributions amount",
	A26270 : "Partnership/S-corp net income (less loss) amount",
	A59660 : "Earned income credit amount",
	A59720 : "Excess earned income credit (refundable) amount",
	A85300 : "Net investment income tax",
	A85530 : "Additional Medicare tax",
	A85770 : "Total premium tax credit amount",
	A85775 : "Advance premium tax credit amount",
	ELDERLY : "Number of elderly returns",
	mars1 : "Number of single returns",
	MARS2 : "Number of joint returns",
	MARS4 : "Number of head of household returns",
	N00200 : "Number of returns with salaries and wages",
	N00300 : "Number of returns with taxable interest",
	N00600 : "Number of returns with ordinary dividends",
	N00650 : "Number of returns with qualified dividends",
	N00700 : "Number of returns with state and local income tax refunds",
	N00900 : "Number of returns with business or professional net income (less loss)",
	N01000 : "Number of returns with net capital gain (less loss)",
	N01400 : "Number of returns with taxable individual retirement arrangements distributions",
	N01700 : "Number of returns with taxable pensions and annuities",
	N02300 : "Number of returns with unemployment compensation",
	N02500 : "Number of returns with taxable Social Security benefits",
	N02900 : "Number of returns with total statutory adjustments",
	N03150 : "Number of returns with IRA payments",
	N03210 : "Number of returns with student loan interest deduction",
	N03220 : "Number of returns with educator expenses",
	N03230 : "Number of returns with tuition and fees deduction",
	N03240 : "Returns with domestic production activities deduction",
	N03270 : "N03270",
	N03300 : "Number of returns with self-employment retirement plans",
	N04470 : "Number of returns with itemized deductions",
	N04800 : "Number of returns with taxable income",
	N05780 : "Number of returns with excess advance premium tax credit repayment",
	N05800 : "Number of returns with income tax before credits",
	N06500 : "Number of returns with income tax",
	N07100 : "Number of returns with total tax credits",
	N07180 : "Number of returns with child and dependent care credit",
	N07220 : "Number of returns with child tax credit",
	N07230 : "Number of returns with nonrefundable education credit",
	N07240 : "Number of returns with retirement savings contribution credit",
	N07260 : "Number of returns with residential energy tax credit",
	N07300 : "Number of returns with foreign tax credit",
	N09400 : "Number of returns with self-employment tax",
	N09600 : "Number of returns with alternative minimum tax",
	N09750 : "Number of returns with health care individual responsibility payment",
	N10300 : "Number of returns with tax liability",
	N10600 : "Number of returns with total tax payments",
	N10960 : "Number of returns with refundable education credit",
	N11070 : "Number of returns with additional child tax credit",
	N11560 : "Number of returns with net premium tax credit",
	N11901 : "Number of returns with tax due at time of filing",
	N11902 : "Number of returns with overpayments refunded",
	N18300 : "Number of returns with taxes paid",
	N18425 : "Number of returns with State and local income taxes",
	N18450 : "Number of returns with State and local general sales tax",
	N18500 : "Number of returns with real estate taxes",
	N19300 : "Number of returns with mortgage interest paid",
	N19700 : "Number of returns with contributions",
	N26270 : "Number of returns with partnership/S-corp net income (less loss)",
	N59660 : "Number of returns with earned income credit",
	N59720 : "Number of returns with excess earned income credit",
	N85300 : "Number of returns with net investment income tax",
	N85770 : "Number of returns with total premium tax credit",
	N85775 : "Number of returns with advance premium tax credit",
	NUMDEP : "Number of dependents",
	PREP : "Number of returns with paid preparer's signature",
	RAC : "Number of refund anticipation check returns",
	RAL : "Number of refund anticipation loan returns",
	SCHF : "Number of farm returns",
	stub_1 : "$1 under $25,000",
	stub_2 : "$25,000 under $50,000",
	stub_3 : " $50,000 under $75,000",
	stub_4 : "$75,000 under $100,000",
	stub_5 : "$100,000 under $200,000",
	stub_6 : "$200,000 or more",
	TCE : "Number of tax counseling for the elderly (TCE) prepared returns",
	TOTAL_VITA : "Total number of volunteer prepared returns",
	VITA : "Number of volunteer income tax assistance (VITA) prepared returns",
	VITA_EIC : "Number of volunteer prepared returns with Earned Income Credit",
}